version: '3'
services:
  service:
    build:
      context: .
      dockerfile: Dockerfile_service
    volumes:
      - .:/app
  application:
    build:
      context: .
      dockerfile: Dockerfile_application
    ports:
      - 80:5000
    volumes:
      - .:/app
  postgres-container:
    build:
      context: .
      dockerfile: Dockerfile_postgres
    ports:
      - 5432:5432

