version: '3'
services:
  service:
    build:
      context: ./
      dockerfile: service/Dockerfile
    volumes:
      - .:/app
    environment:
      - SERVICE_ENDPOINT=http://application:5000/add
  application:
    build:
      context: ./
      dockerfile: application/Dockerfile
    ports:
      - 80:5000
    volumes:
      - .:/app
    environment:
      - POSTGRESQL_USER=postgres
      - POSTGRESQL_PASSWORD=postgres
      - POSTGRESQL_DATABASE=coindb
  postgres-container:
    build:
      context: ./postgres
      dockerfile: Dockerfile
    ports:
      - 5432:5432
    volumes:
      - ./init-db:/docker-entrypoint-initdb.d

