version: '3'
services:
  application:
    build:
      context: .
      dockerfile: Dockerfile_application
    ports:
      - 80:5000
    volumes:
      - .:/app
  postgres-container:
    build:
      context: .
      dockerfile: Dockerfile_postgres

