version: '3'
services:
  service:
    build:
      context: ./
      dockerfile: service/Dockerfile
    volumes:
      - .:/app
  application:
    build:
      context: ./
      dockerfile: application/Dockerfile
    ports:
      - 80:5000
    volumes:
      - .:/app
  postgres-container:
    build:
      context: ./postgres
      dockerfile: Dockerfile
    ports:
      - 5432:5432

